### PR TITLE
Add missing string to firefox/campaign.lang

### PR DESCRIPTION
**Pull request by alexgibson**
I accidentally removed a required string in #278 that I (naively) assumed was in `main.lang`. This PR adds it back, copying the existing translation from `firefox/new/quantum.lang`

### CODE REVIEW

**Comment by flodolo** [comment]
Out of curiosity, how did you copy it?

**Comment by alexgibson** [comment]
> Out of curiosity, how did you copy it?

I burned an hour of my life going through folder by folder and doing it manually (lesson learned).

Thanks @flodolo 👍

**Comment by flodolo** [comment]
> I burned an hour of my life going through folder by folder and doing it manually (lesson learned).

For the future, that's one script available in langchecker
https://mozilla-l10n.github.io/documentation/tools/webdashboards/import_translations.html

Hopefully we'll have the overview doc finished by next week, and we can start onboarding you folks.

**Comment by flodolo** [comment]
Double checked locally that there were no differences with the automated import.

**Comment by alexgibson** [comment]
That's great to hear (re: the script), thanks again @flodolo

**Pull request merged**
