### PR TITLE
Add new strings for accounts-2019.lang

### PR DESCRIPTION
**Pull request by alexgibson**
Adds new strings for https://github.com/mozilla/bedrock/pull/7318

### CODE REVIEW

**Comment by alexgibson** [comment]
Extracted locales, mergins thanks!

**Comment by alexgibson** [comment]
@peiying2 should I manually enable this new tag for all en-locales before I merge?

**Comment by peiying2** [comment]
> @peiying2 should I manually enable this new tag for all en-locales before I merge?

No need. We will use Pontoon to do the work.

**Comment by alexgibson** [comment]
Pushed to prod in https://github.com/mozilla-l10n/bedrock-l10n/commit/271023df64cf5a8e749ccbb4a9d4edbd72380287

**Pull request merged**
