### PR TITLE
Update hello-2016.lang

### PR DESCRIPTION
**Pull request by fuzz139**

### CODE REVIEW

**Comment by flodolo** [comment]
CC @chikoski @kyoshino

**Comment by kyoshino** [comment]
I have already localized the string in https://github.com/mozilla-l10n/www.mozilla.org/commit/37eb370e7dd0e94cb633895386706c4f3c45c9d1

**Comment by kyoshino** [comment]
Why this commit is not conflicting, btw?

**Comment by flodolo** [comment]
I think because the change is the same. It basically did an empty merge.

**Pull request merged**
