### PR TITLE
Updates pt-BR webdev email template

### PR DESCRIPTION
**Pull request by dirtycoder**

### CODE REVIEW

**Comment by flodolo** [comment]
@ouesten Can you take a look? This file is not available through Pontoon

**Comment by dirtycoder** [comment]
@ouesten maybe I should add this note:
I used as some kind of template the en-US and pt-PT versions of this file.

**Comment by flodolo** [comment]
Let's try with @reuben Can you take a look at this PR?

**Comment by reuben** [comment]
r=me with the Gaia text (lines 11-14) removed.

**Comment by flodolo** [comment]
I realized this PR was never merged. At this point I'm going to close it, since we're going to get rid of emails and autoresponders in the near future (before the end of the month).

**Pull request closed without merging**
