### PR TITLE
Update /firefox/new/trailhead.lang

### PR DESCRIPTION
**Pull request by alexgibson**
Ref: https://github.com/mozilla/bedrock/pull/7383

### CODE REVIEW

**Comment by alexgibson** [comment]
@peiying2 I updated the URL to point to dev. Click on "Download Now" using Firefox and you'll see the new strings.

**Comment by peiying2** [comment]
Great! Go ahead with rebase, update localized file and merge.

**Comment by alexgibson** [comment]
@peiying2 extracted locale strings. Can you please check I've done that right? (I can't remeber if it's expected for the tag comments not to be there).

**Comment by alexgibson** [comment]
Ok I worked it out by comparing what happens to other files. Things look good, merging!

**Comment by peiying2** [comment]
> @peiying2 extracted locale strings. Can you please check I've done that right? (I can't remeber if it's expected for the tag comments not to be there).

This is the correct (but confusing) behavior. The localized file has no tags at the string level or at the beginning of the file. Once the tagged strings are localized, the tag at the beginning of the file will show up.

Examples:
- Updates localized: https://github.com/mozilla-l10n/www.mozilla.org/blob/master/**de**/firefox/accounts-2019.lang
- Untranslated: https://github.com/mozilla-l10n/www.mozilla.org/blob/master/af/firefox/accounts-2019.lang

Both missing the tags at string level, but German has the tag at the beginning of the file, indicating the updates are now on production.

**Comment by alexgibson** [comment]
Makes sense, thanks @peiying2!

Pushed to production in https://github.com/mozilla-l10n/bedrock-l10n/commit/36bc69cede301a5518741ba45d14e19ddaf21b79

**Pull request merged**
