### PR TITLE
nl/firefox/whatsnew_67.lang l10n

### PR DESCRIPTION
**Pull request by oeekker**

### CODE REVIEW

**Comment by flodolo** [comment]
@oeekker 
Can we use Pontoon for this? Also see the email that I've sent to the Dutch translators
https://pontoon.mozilla.org/nl/mozillaorg/

**Comment by oeekker** [comment]
Hi Francesco,

No problem for me to enable this project (and others like Firefox for iOS)
in Pontoon!

Onno

**Comment by flodolo** [comment]
Mozilla.org is already there
https://pontoon.mozilla.org/nl/mozillaorg/

Could you request the one missing via Pontoon if you want to work there?

Il ven 19 apr 2019, 08:08 Onno Ekker <notifications@github.com> ha scritto:

**Comment by oeekker** [comment]
Mozilla.org is a read-only localization, that's why I translated it on
github.

**Comment by flodolo** [comment]
Let's merge this one. I've just enabled mozilla.org as normal project on Pontoon, not sure if the current sync will pick this up, or we need to wait for 12:50

Also enabled Firefox for iOS.

**Pull request merged**
