### PR TITLE
Add new banner description with provided copy

### PR DESCRIPTION
**Pull request by Errolyn**
issue: 

https://github.com/mozilla/bedrock/issues/8195 

and copy 

https://docs.google.com/document/d/1VQwpJKfBBFZnNzYtme4XxxuSX1CbMp4mDQ4BOvrSEhM/edit

### CODE REVIEW

**Comment by peiying2** [comment]
@Errolyn please follow the tagging format like this one: https://github.com/mozilla-l10n/www.mozilla.org/blob/master/en-US/firefox/all.lang#L40

**Comment by flodolo** [comment]
This file is exposed to all locales. Why was the string not added to all other languages in this pull request?

**Comment by Errolyn** [comment]
The banner only shows up for the languages I added, if we add them to the other files then it will get translated but never seen.

**Comment by flodolo** [comment]
Unfortunately that's not how the system works. If you add a string to en-US, it gets exposed to all languages enabled for that file, and it should be added in the pull request.

Note that the string was already added in a completely unrelated commit later
https://github.com/mozilla-l10n/www.mozilla.org/commit/5479f0e9b837c0916b23b551c60ff20044ac5789

**Comment by Errolyn** [comment]
I'm confused the commit you linked is only adding that string to all of the different Lang files from what I can see, was that commit in a OR that was unrelated? 

Also is there an action item needed from me on this? I'm on holiday but if there is some thing I need to do/fix I'm happy to do so.

**Comment by flodolo** [comment]
There's no action needed at this point, but you and Peiying should sync on this.

**Pull request merged**
