### PR TITLE
nb-NO: various random new translations and updates

### PR DESCRIPTION
**Pull request by andreastt**

### CODE REVIEW

**Comment by flodolo** [comment]
Thanks Andreas. Are you already in touch with the [localization team](https://wiki.mozilla.org/L10n:Teams:nb-NO)? I'm going to send an email to Håvard to ping him.

**Comment by andreastt** [comment]
Split into multiple logical commits, and rebased.

**Comment by andreastt** [comment]
@flodolo ping

**Comment by flodolo** [comment]
I'm not the right person to ping: it's up to the team to look at this and merge, not me ;-)

**Comment by andreastt** [comment]
@flodolo I’m not sure what that means.  What is “the team” in this context?

**Comment by flodolo** [comment]
The link above: the team in charge of the nb-NO localization
https://wiki.mozilla.org/L10n:Teams:nb-NO

**Comment by havarh** [comment]
This looks great! There is however a couple of changes that needs to be made. First: "Do Not Track", you use "Sporingsløs" while we use "Ikke spor" in the products.
I also see that you've added commas before "og". I don't think there should be any commas before "og", as seen here:
http://www.korrekturavdelingen.no/K4kommaRegler.htm
No oxford comma in Norwegian.
You've used "Privatmodus" for "Privat browsing", while we use "Privat nettlesing" in our translations.
I see that you've fixed "Themes", it was translated as "Temaer", while you've corrected it to "Utseende" which is also the wording we use in Firefox/Thunderbird.
I'll have to read some more trough your pull request.
PS! If there is any terminology that you're unsure about, you could use Mozilla Transvision at:
transvision.mozfr.org to check what terminology is already used in the products.

**Comment by andreastt** [comment]
@havarh I have addressed the issues you raised. Thank you for the review so far!

I ascribe the misuse of commas to years living abroad. (-:

**Comment by flodolo** [comment]
@havarh 
Let me know if you want to double check and merge, otherwise I'll merge in the next days.

**Comment by havarh** [comment]
Some more small changes:
- **+%d.%m.%y** <- I think y needs to be in uppercase, like: **%d.%m.%Y**
- Creative Commons **license** <- We could use the norwegian word: "**lisens**" here
- **"Skru på JavaScript for at denne sidnen skal vises korrekt."** <- removing **"Vær så snill å"**, we're not using "Please" in the Norwegian translation. I've forgotten why we're not doing that. But it might be that we're less formal?
- **"almenyttige"** is written with two **N**s, **"almennyttige"**
- **"En av våre programmerere vil ta en kikk snart"** I'd use "utviklere" instead of "programmerere"

**Comment by havarh** [comment]
I found out why we're not using "**please**" in Norwegian:
> Engelsk brukar svært ofte «please», mens på norsk treng me sjeldan bruka ordet i det heile. Me er ikkje mindre høflege; me berre uttrykkjer det på andre måtar.
Quote from:
http://i18n.skulelinux.no/retningslinjer.html

**Comment by andreastt** [comment]
@havarh Fixed in 6f4313e...762b529.

**Comment by andreastt** [comment]
@havarh Can this be merged now?

**Comment by havarh** [comment]
@andreastt yes, it could.

**Comment by flodolo** [comment]
Thanks both.

**Pull request merged**
