### PR TITLE
Add browser-history.lang

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
Ok @peiying2 I think this is ready for review.

**Comment by peiying2** [comment]
@alexgibson LGTM. Let's populate the strings to the locale files.

**Comment by alexgibson** [comment]
@peiying2 locale files populated, thanks.

**Comment by flodolo** [comment]
Is anything blocking this?

**Comment by alexgibson** [comment]
Oh sorry, I didn't realise I needed to merge this myself.

**Comment by flodolo** [comment]
Can you also do the cherry-pick to production? It's documented, and you should have access to the repo.

**Comment by alexgibson** [comment]
So just to be clear on the next steps: I need to make a production push for these strings now? They don't need to wait to be localized?

**Comment by flodolo** [comment]
Yes. The files are not localized, so they're not active.

**Comment by alexgibson** [comment]
The documentation lists tools I don't have available on my platform: https://mozilla-l10n.github.io/documentation/products/mozilla_org/updating_mozillaorg_production.html

My current thought to do this manually would be to add a remote to dev from the prod repo:

```
git remote add dev https://github.com/mozilla-l10n/www.mozilla.org
git fetch dev
```

Then I could `git cherry-pick` the hash from dev. 

Does that sound sensible?

**Comment by flodolo** [comment]
Yes. If you dig into the repository, you'll find a script that set up the
remote for prod, and a list of all the aliases.

Il mer 17 apr 2019, 18:13 Alex Gibson <notifications@github.com> ha scritto:

**Comment by alexgibson** [comment]
> Yes. If you dig into the repository, you'll find a script that set up the remote for prod, and a list of all the aliases.

Which repository does this script live in? Sorry if I'm being blind.

**Comment by alexgibson** [comment]
Also, should I just do this an push to master, or would you prefer a pull request?

**Comment by alexgibson** [comment]
Until I'm really clear on what I should be doing, I'm hesitant to make any changes. It would be great to have some clear manual steps for this on https://mozilla-l10n.github.io/documentation/products/mozilla_org/updating_mozillaorg_production.html

**Comment by peiying2** [comment]
> Also, should I just do this and push to master, or would you prefer a pull request?
For the production push, you can push directly to the master. The page won't be activated until it is fully localized.

**Comment by flodolo** [comment]
> Until I'm really clear on what I should be doing, I'm hesitant to make any changes. It would be great to have some clear manual steps for this on https://mozilla-l10n.github.io/documentation/products/mozilla_org/updating_mozillaorg_production.html

The same document has a link to
https://mozilla-l10n.github.io/documentation/config/setup_l10ndrivers_vm.html

Which has links to the scripts repository
https://github.com/mozilla-l10n/vm_scripts

I think I pointed to it already at some point in our conversations
https://github.com/mozilla-l10n/vm_scripts/blob/master/setup_vm/setup_repositories.sh#L17-L20
https://github.com/mozilla-l10n/vm_scripts/blob/master/.bashrc_aliases

The documentation is open for edits, feel free to add whatever you think it's useful for your team.

The workflow should be:
* Get approval on the en-US changes in your PR
* Rebase against master before adding other locales. That's crucial for changes to existing files
* Merge and immediately cherry-pick to production. If you don't, you're going to have to deal with conflicts over a commit with potentially hundreds of files

**Comment by alexgibson** [comment]
> If you don't, you're going to have to deal with conflicts over a commit with potentially hundreds of files

Wonderful 😐

**Comment by flodolo** [comment]
> Wonderful 😐

It's a wonderful system, ain't it? That's also why I'd like to have conversation about the actual need for a separate production repository in the first place…

**Comment by alexgibson** [comment]
Yep we had similar questions on why it is like this yesterday. As a developer, this process is honestly quite frightening, as the two repos don’t strictly share commit history. And pushing this straight to master in this way with no review is frankly 😳

**Comment by alexgibson** [comment]
Also, this is really not adequately documented. Pages that link to other pages, to other repos, that have some script buried somewhere is kinda confusing for people who aren’t familiar with the project or workflow.

**Comment by flodolo** [comment]
It's a workflow that we want to dismiss. I think making sure it has information for the transition period is one thing, reorganizing or rewriting it from scratch is not in scope at this point. It was never designed to be shared outside of our team.

**Comment by alexgibson** [comment]
> It was never designed to be shared outside of our team.

Well, here we are. Be prepared for some hand-holding 😉

**Comment by alexgibson** [comment]
Comitted https://github.com/mozilla-l10n/bedrock-l10n/commit/363b08c7434efe519729aed28f6448c4b83d4169

Don't _think_ I blew anything up. Am going to work on a PR to update your docs with the steps I followed.

**Comment by flodolo** [comment]
> Don't _think_ I blew anything up. Am going to work on a PR to update your docs with the steps I followed.

Nothing can blow up, since all files all added "inactive" by scripts. It's just very cumbersome, especially if there are updates to the repo in the meantime, or stage and prod are out of sync. Thanks for the PR, will look in. abit.

**Pull request merged**
