### PR TITLE
[ja] Remove broken translation

### PR DESCRIPTION
**Pull request by mathjazz**
@flodolo r?

### CODE REVIEW

**Comment by flodolo** [comment]
I wonder if that's a way to trick the system. 

Replacing the string with English is not OK, it will display in the page. My guess is that they don't want this string at all, but if they leave it empty the system will complain about the missing string and display English text. If they leave an empty space as translation, it will be trimmed and the English string restored.

@chikoski Any explanation about this string?

**Comment by flodolo** [comment]
Found the explanation
https://github.com/mathjazz/www.mozilla.org/commit/c28245794a401847c8f60d743833c77b0b2f4fb9#diff-2e067f5b87806a203e51958bb7821665

**Comment by mathjazz** [comment]
Huh, I didn't know this was still a valid .lang file. It breaks Pontoon parser, cusing it to skip this resource for this locale. I wonder what should we do instead? Allow empty translations for .lang files (like we do for some other formats) and then serialize it as {ok}?

**Comment by flodolo** [comment]
That would be a huge change, not just our tools but all websites that use .lang files.

One possible solution would be to use a special utf-8 character like U+200B, but we need to check what happens with Bedrock. Let me try it.
http://www.fileformat.info/info/unicode/char/200B/index.htm

**Comment by flodolo** [comment]
It doesn't work, it's still trimmed. I'll add an empty comment instead
https://github.com/mozilla-l10n/www.mozilla.org/commit/743dea924a435a34a35012aeaca38a9d3f612aae

@mathjazz Does it work for you?

**Comment by mathjazz** [comment]
Yeah, that commit help. Pontoon imports translation as .

**Comment by pascalchevrel** [comment]
you could probably also use a zero width html entity such as &zwnj;

**Comment by flodolo** [comment]
`&zwnj;` is definitely better for the markup, but I'm a bit afraid about potential issues like (and I didn't thought about it when I suggested to add the utf-8 version)
http://stackoverflow.com/questions/12354414/zero-width-non-joiner-zwnj-shown-as-pipe-in-ie7

**Pull request closed without merging**
