### PR TITLE
TL Localization for features

### PR DESCRIPTION
**Pull request by heywens**

### CODE REVIEW

**Comment by flodolo** [comment]
@heywens 
Thank you very much for your contribution. Have you already tried to get in touch with the [Tagalog team](https://wiki.mozilla.org/L10n:Teams:tl)?

@bobreyes @cyrixware
Can you take a look at this pull request?

**Comment by heywens** [comment]
Hello Sir @flodolo, sorry if I didn't know that there's a Tagalog team for this localization. I'll check it out and will try to coordinate them.

Thank you.

**Comment by flodolo** [comment]
> Hello Sir @flodolo, sorry if I didn't know that there's a Tagalog team for this localization. I'll check it out and will try to coordinate them.

No worry, that's great to see new contributors :)

**Comment by bobreyes** [comment]
Thanks, @flodolo! Hi, @heywens will ping you. Thanks!

**Comment by heywens** [comment]
Okay Sir @bobreyes, thanks!

**Comment by bobreyes** [comment]
@heywens if you can please shoot me a message via bob@mozillaph.org thanks! (can't send you a message from here)

**Comment by heywens** [comment]
I've sent an invite on Google Hangout, would that okay Sir @bobreyes?

**Pull request closed without merging**
