### PR TITLE
update files per PRs 5376, 5378, and 5382

### PR DESCRIPTION
**Pull request by peiying2**

### CODE REVIEW

**Comment by peiying2** [comment]
Looks like we have all the strings for PR5381. Nothing to be done on our end, correct?

Also, on the technology.lang file, to deactivate the file, do you remove the entry from the script: https://github.com/mozilla-l10n/vm_scripts/blob/master/update_mozillaorg.sh? Then run the script (or somehow) so the files are deactivated? Then add the entry back in? I am curious, :).

**Comment by flodolo** [comment]
> Looks like we have all the strings for PR5381. Nothing to be done on our end, correct?

Yes. It was marked for the removal of strings, but they're generic enough that we should keep them.

> Also, on the technology.lang file, to deactivate the file, do you remove the entry from the script: https://github.com/mozilla-l10n/vm_scripts/blob/master/update_mozillaorg.sh? Then run the script (or somehow) so the files are deactivated? Then add the entry back in? I am curious, :).

There's a script in langchecker called `mark_not_active` that removes it. Then you run `mark_active` again, at that point it will enable only complete files.

**Comment by flodolo** [comment]
PR5382 has a do not merge tag, and `Do not merge until I get the strings and styling approved.`.

If you want to merge this one, we should remove that change from the PR. The alternative is to keep it on hold until that PR is approved.

**Comment by peiying2** [comment]
If nothing in this PR is urgent, we can wait until PR5382 is ready.

**Comment by peiying2** [comment]
@flod, this is the German only file. I couldn't run the script even with the patch to extract the file, so I manually copy/paste the strings. One thing I notice missing is this one:  https://github.com/mozilla/bedrock/pull/5400/files#diff-ebe89cb8916b591a0070ef5f00859c0bR38. I added to the file. Let me know if this is incorrect so I can remove it.

**Comment by flodolo** [comment]
Did you import the patch locally to extract the file? What's the error when you run the script to extract strings?

**Comment by flodolo** [comment]
Also, at this point we're blocked by 5382, which is not ready to be exposed. You have to drop it from this PR, or use a different branch for 5400

**Comment by peiying2** [comment]
Let's drop this PR then. The page needs to go out on 1/23 though.

**Comment by flodolo** [comment]
> Let's drop this PR then. The page needs to go out on 1/23 though.

Don't forget to remove the switch file from this PR

**Comment by flodolo** [comment]
I'm moving the pending PR in a different branch, you will just need to "git pull" and checkout that branch to start working on it when it's ready.
https://github.com/mozilla-l10n/www.mozilla.org/tree/pr5382

**Pull request merged**
