### PR TITLE
Update zh-tw contribute form reply, coding.txt add rust/servo/b2g, remove fxos info

### PR DESCRIPTION
**Pull request by irvin**

### CODE REVIEW

**Comment by flodolo** [comment]
Hi Irvin, these files need to be removed (I'm going to do it right now, to avoid any further confusion).

We removed the /contribute contact form a couple of weeks ago, so there are currently no autoresponders used.

**Comment by irvin** [comment]
@flodolo No there are still embed form using the reply content. Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1271422#c13

**Comment by flodolo** [comment]
Argh 👎 

Right now my connection doesn't reach Bugzilla, but I'll restore the files at this point. I wasn't aware of this, and I'm not sure why we have embedded forms like this.

**Comment by flodolo** [comment]
Argh 👎 

Right now my connection doesn't reach Bugzilla, but I'll restore the files at this point. I wasn't aware of this, and I'm not sure why we have embedded forms like this.

**Comment by irvin** [comment]
Thanks!

The embed form is used by many local sites such as Taipei office (at  http://mozilla.com.tw/community/contribute/ ), thus we can have a unified experience and contributor database across every different region / community.

**Pull request merged**
