### PR TITLE
Add firefox/accounts-2019.lang for Trailhead

### PR DESCRIPTION
**Pull request by craigcook**
Compare to the rough template in https://github.com/mozilla/bedrock/pull/7197 (not final code or layout but strings should be complete).

### CODE REVIEW

**Comment by craigcook** [comment]
So I'm not sure how best to do the next step... I think the intent is to get DE and FR done first, then expose it to all other locales. So maybe the way to go about that is to go ahead and copy this file to all locales, but initially only expose these strings for DE and FR in the langchecker sources file, then update that sources file later to spread it to all the others. Will that work?

**Comment by peiying2** [comment]
> So I'm not sure how best to do the next step... I think the intent is to get DE and FR done first, then expose it to all other locales. So maybe the way to go about that is to go ahead and copy this file to all locales, but initially only expose these strings for DE and FR in the langchecker sources file, then update that sources file later to spread it to all the others. Will that work?

In langchecker, we can add `de`, `fr`, and `en-*` locales only initially, but we can open it up to the rest at a later time. Once we expose the locales, we can't hide them in Pontoon. It has to be a two step process if we want to control it that way.

Is it possible to hide the other locales from pushed to production until Bedrock enables it? On l10n side, we can "activate" the page in Bedrock-l10n, but the ultimate activation to the website can be controlled at the Bedrock code level. This way we give communities time to localize.

**Comment by flodolo** [comment]
> So maybe the way to go about that is to go ahead and copy this file to all locales, but initially only expose these strings for DE and FR in the langchecker sources file, then update that sources file later to spread it to all the others. Will that work?

No, never do that. If the file shows up on GitHub, it shows up on Pontoon. With the issue that is not tracked for errors or activation.

**Comment by craigcook** [comment]
> No, never do that. If the file shows up on GitHub, it shows up on Pontoon. With the issue that is not tracked for errors or activation.

Ah, I thought the langchecker sources file was how we controlled what appeared in Pontoon. So instead I should only copy this lang file to DE and FR (and en-GB and en-CA, though I doubt they'll required any changes, just activation) and we can copy it to the rest later, once those are complete. Correct? I'll do that

> Is it possible to hide the other locales from pushed to production until Bedrock enables it? On l10n side, we can "activate" the page in Bedrock-l10n, but the ultimate activation to the website can be controlled at the Bedrock code level. This way we give communities time to localize.

In bedrock I'm using `lang_file_is_active` to determine which locales get the new page and others will fall back to the previous page.

**Comment by flodolo** [comment]
> So instead I should only copy this lang file to DE and FR (and en-GB and en-CA, though I doubt they'll required any changes, just activation) and we can copy it to the rest later, once those are complete. Correct? I'll do that

You need a PR in langchecker that tracks this file for just de and fr. Then run the script to add the actual files to your PR.

**Comment by craigcook** [comment]
Added https://github.com/mozilla-l10n/langchecker/pull/882

**Comment by peiying2** [comment]
@craigcook please merge to master and push to production.

**Pull request merged**
