### PR TITLE
PR 6528: CPG update plus add new file

### PR DESCRIPTION
**Pull request by peiying2**
@flodolo: this project will go to an agency. If you have no time to review it before departing to all hands, we can work on it some time next week. I will need to send an email about not touching it. Or I can turn it to read-only while the files go out to translation.

### CODE REVIEW

**Comment by flodolo** [comment]
How are agencies supposed to work on this file? Via Pontoon or via .lang files?

> Or I can turn it to read-only while the files go out to translation.

What does this mean?

**Comment by flodolo** [comment]
The two files look good, but first I need to understand what you want to do.

**Comment by peiying2** [comment]
How are agencies supposed to work on this file? Via Pontoon or via .lang files?

When the first version was made available, we had the agency download the files from Pontoon (or I did it) and same with uploading. I sent an email about this project and told everyone to treat it like a legal doc - not to touch it. Community can still review it afterwards, which some did do.  There are only a few locales. Last time it was not activated until each gave a go-ahead.

       Or I can turn it to read-only while the files go out to translation.

   What does this mean?

I over stated on this. We can't change a locale to "read only" at file level. It works at project level, so this approach won't work.  Will send an email asking communities not to touch it before it is fully localized. For the update, the file is activated already.

**Comment by flodolo** [comment]
OK, that makes sense. We need a corresponding PR in langchecker though, to add the new file to affected languages.

**Pull request merged**
