### PR TITLE
Add /firefox/new/trailhead.lang

### PR DESCRIPTION
**Pull request by alexgibson**
Bedrock PR: https://github.com/mozilla/bedrock/pull/7187
Langchecker PR: https://github.com/mozilla-l10n/langchecker/pull/881

### CODE REVIEW

**Comment by alexgibson** [comment]
@peiying2 the ask here is for `en`, `de`, and `fr` locales as a priority (someone in Marketing will provide the `de` translation once this is in Pontoon). All other locales are requested, but not as critical for launch.

**Comment by ejregithub** [comment]
@peiying2 - correction to request - as you documented in email - FR is going through Agency and MJ has the request for that.  Please review this doc that is being provided for the localization company (MotherTongue, iirc) - https://docs.google.com/spreadsheets/d/1qQRNxgt_BiF2pqFvsCIb5c_2QbrUlO0NY0JakgpQ_r4/edit#gid=757298539

**Comment by alexgibson** [comment]
@ejregithub the doc you link to above looks incomplete. Please see the actual strings in the pull request above.

**Comment by ejregithub** [comment]
Will do, thanks @alexgibson

**Comment by peiying2** [comment]
@alexgibson @ejregithub Given this PR is made available now, we are checking French community to see if they want to work on this. Waiting for their answer.

**Comment by peiying2** [comment]
@alexgibson Everything looks good. One thing we used to do often was removing strings already existing in "shared" files. I see a few in this file. If we were to decide to let Pontoon pop up suggestions when detecting the same or similar strings, it will save us time when prepping files.

**Comment by alexgibson** [comment]
> @alexgibson Everything looks good. One thing we used to do often was removing strings already existing in "shared" files. I see a few in this file. If we were to decide to let Pontoon pop up suggestions when detecting the same or similar strings, it will save us time when prepping files.

I'm not quite clear on what you would like me to do here - is the ask to remove some strings (if so, which ones?), or are we ok lean on Pontoon's suggestions?

**Comment by alexgibson** [comment]
Pushed to production in https://github.com/mozilla-l10n/bedrock-l10n/commit/20375eca0b289cb306409700fd61851ba1e878a3

**Comment by ejregithub** [comment]
@alexgibson - this copy contains the final copy - https://docs.google.com/document/d/1F-hIja0JTQTHEK0_zKEFL8vRBBfYK4-LdqzaS-hSvN4/edit  

It contains the most up-to-date strings that will require changes [to the pull request](https://github.com/mozilla-l10n/www.mozilla.org/pull/296/commits/2ca5fa8c8513f397e836746db2f680404b3cd781).

**Comment by flodolo** [comment]
> It contains the most up-to-date strings that will require changes [to the pull request](https://github.com/mozilla-l10n/www.mozilla.org/pull/296/commits/2ca5fa8c8513f397e836746db2f680404b3cd781).

We pushed the strings out for localization, 4 hours before this comment. How did this happen?

**Comment by alexgibson** [comment]
@flodolo don’t worry this was a false alarm. The strings are correct. Eric didn’t expect to see extra strings in the Lang file, as the original copy doc didn’t include every piece of copy in the real template.

**Pull request merged**
