### PR TITLE
Added localization for TL

### PR DESCRIPTION
**Pull request by bobreyes**

### CODE REVIEW

**Comment by flodolo** [comment]
@bobreyes 
Interesting, Tagalog is currently set to work in Pootle but it's not available there.

Can I suggest to enable it in Pontoon instead?

**Comment by bobreyes** [comment]
@flodolo yes, please enable it in Pontoon. I just clicked on the link in the Dashboard [https://l10n.mozilla-community.org/webdashboard/?locale=tl] which eventually led me to the Github repo. Thanks!

**Comment by flodolo** [comment]
Great, I'll merge this one, so Pontoon will pick up the strings. It should be available within the next 15-20 minutes.

**Comment by bobreyes** [comment]
Thank you very much @flodolo

**Pull request merged**
