### PR TITLE
Remove accounts.lang

### PR DESCRIPTION
**Pull request by alexgibson**
Ref: https://github.com/mozilla/bedrock/pull/7363

@peiying2 We're retiring a legacy page in the PR above, so this lang file will no longer be required. Can you please advice on the process for removing a file? Thanks

### CODE REVIEW

**Comment by alexgibson** [comment]
Note: I understand we'll be losing some locales with this change, but this template is over 2 years old and the 2018 template has already been superceded in 2019. The locales that haven't already updated can hopefully catch up if they notice their page is no longer translated.

**Comment by peiying2** [comment]
@alexgibson We have a doc covering this topic: https://github.com/mozilla-l10n/documentation/blob/master/tools/webdashboards/remove_obsolete_files.md. 
We have a monthly l10n report coming up. I will mention about the change so the communities can catch up with 2019 version.

**Comment by alexgibson** [comment]
@peiying2 thank you - I'll follow these instructions when ready.

**Comment by alexgibson** [comment]
@peiying2 I followed the docs and removed the files here. This should be OK to merge once the langchecker PR has merged.

**Comment by alexgibson** [comment]
Ok, once someone reviews this it should not be good to merge

**Comment by alexgibson** [comment]
Pushed to prod in https://github.com/mozilla-l10n/bedrock-l10n/commit/f365a46529f52e103efc8a93eb409ef27a7e0dad

**Pull request merged**
