### PR TITLE
Add what-is-a-browser.lang

### PR DESCRIPTION
**Pull request by alexgibson**
Re: https://github.com/mozilla/bedrock/pull/7120

Langchecker PR: https://github.com/mozilla-l10n/langchecker/pull/878

### CODE REVIEW

**Comment by peiying2** [comment]
Let's go ahead to add locale files and merge

**Comment by alexgibson** [comment]
Can you please merge the langchecker PR? Then I can add the locale files. thanks

**Comment by alexgibson** [comment]
@peiying2 I extracted the files locally. Is it ok to merge, even though the langchecker PR hasn't merged yet?

**Comment by peiying2** [comment]
@alexgibson I just did. Please go ahead with the merge and production push.

**Comment by alexgibson** [comment]
Pushed to production in https://github.com/mozilla-l10n/bedrock-l10n/commit/790155a68146e81b279d61d2e22d24746b80857a

**Pull request merged**
