### PR TITLE
Corneliu Rusu (HTP): Localized participation.lang

### PR DESCRIPTION
**Pull request by CorneliuRusu**

### CODE REVIEW

**Comment by flodolo** [comment]
CC @kyoshino 

For reference, there was a double translation, no clue which one was supposed to be used
https://github.com/mozilla-l10n/www.mozilla.org/commit/100f0655e9a81c9878f9cc0ff379a342132c884c#diff-614759786b74c6648fac264d43a042e8L128

**Comment by kyoshino** [comment]
Hmm, looks like there was an unnecessary line break between those two lines that was supposed to be one single line. Not a double translation.

**Comment by kyoshino** [comment]
Fixed in https://github.com/mozilla-l10n/www.mozilla.org/commit/8c48e5be0bed81269cc588f56b23a044901c3c74

**Comment by flodolo** [comment]
Thanks 👍

**Pull request merged**
