### PR TITLE
Update developer-quantum.lang

### PR DESCRIPTION
**Pull request by markh-bz**
Added translations for the new strings. Feel free to shoot and amend ;)

### CODE REVIEW

**Comment by peiying2** [comment]
@markh-bz I can merge the PR. If you need another contributor to review it before I do, let me know.

**Comment by markh-bz** [comment]
Hi Peiying, 

Normally, Tonnes would review, merge and commit, to ensure Qa is
properly done ;) 

See you, Mark 

Peiying schreef op 2017-09-27 18:03: 

> @markh-bz [1] I can merge the PR. If you need another contributor to review it before I do, let me know. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/markh-bz
[2]
https://github.com/mozilla-l10n/www.mozilla.org/pull/194#issuecomment-332571420
[3]

**Comment by peiying2** [comment]
@markh-bz the English source has been updated since. Shall we close the PR and check what the latest is?

**Comment by markh-bz** [comment]
Yes please

**Pull request closed without merging**
