### PR TITLE
Add L10n comment to /firefox/new/quantum.lang

### PR DESCRIPTION
**Pull request by alexgibson**
New L10n comment added in https://github.com/mozilla/bedrock/pull/6977

### CODE REVIEW

**Comment by peiying2** [comment]
@alexgibson LGTM.

**Comment by alexgibson** [comment]
@peiying2 thanks - I'm trying to figure out the required workflow for updating files, so I thought this would be a good one to start with.

My understanding is as follows:

1. In order to add the comment to the other lang files, I need to [fork another repo](https://github.com/mozilla-l10n/langchecker) and then somehow run the `lang_update` script in that repo on the files in this repo. Is that correct? If that's the case, what are the recommended steps to run the script? (do I really need to set up PHP on my local machine?). This would be useful documentation for our team if we need to do this.
2. Once I manage to add the comment to the other l10n files, I then commit those here before we merge.
3. I then need to fork the [production repo](https://github.com/mozilla-l10n/bedrock-l10n) and cherry-pick the commit from here to there. Is the best way to go about that by adding the production repo as a git `remote`, and then using `git cherry-pick`? (again useful for documentation).

Thanks for your patience :)

**Comment by flodolo** [comment]
> * In order to add the comment to the other lang files, I need to [fork another repo](https://github.com/mozilla-l10n/langchecker) and then somehow run the `lang_update` script in that repo on the files in this repo. Is that correct? If that's the case, what are the recommended steps to run the script? (do I really need to set up PHP on my local machine?). This would be useful documentation for our team if we need to do this.

Yes, you need PHP and to configure Langchecker locally. Having said that: unless you're on Windows, you either have it bundled in the OS (macOS), although I suggest a more recent version with homebrew, or it's only a few packages away (Linux).

For you folks, it might be easy to set up a VM or even a Docker image to run these scripts.

Have you already seen this, and the connected documents?
https://mozilla-l10n.github.io/documentation/products/mozilla_org/extract_strings.html

> * Once I manage to add the comment to the other l10n files, I then commit those here before we merge.

Yes

> * I then need to fork the [production repo](https://github.com/mozilla-l10n/bedrock-l10n) and cherry-pick the commit from here to there. Is the best way to go about that by adding the production repo as a git `remote`, and then using `git cherry-pick`? (again useful for documentation).

It's documented
https://mozilla-l10n.github.io/documentation/products/mozilla_org/updating_mozillaorg_production.html

Using trunk as remote is only mentioned briefly, because the VM has shortcuts
https://github.com/mozilla-l10n/vm_scripts/blob/master/.bashrc_aliases#L14

And remotes already set up
https://github.com/mozilla-l10n/vm_scripts/blob/master/setup_vm/setup_repositories.sh#L17-L20

**Comment by alexgibson** [comment]
Thanks @flodolo this is the first time I think I've seen this documentation. I'll spend some time reading this, and let you know if I have any questions.

**Comment by alexgibson** [comment]
Ok, here's where I got to:

1. I forked langchecker and installed the dependencies OK.
2. I had to move my fork of `www.mozilla.org` into parent directory which I called `mozilla-l10n`.
3. I then set `$local_storage = '/Users/agibson/Documents/GitHub/mozilla-l10n/';` in `settings.inc.php`.
4. I then ran `./app/scripts/lang_update`.

The output is:

```
Reference English file: /Users/agibson/Documents/GitHub/mozilla-l10n/mozilla_org/en-US/main.lang

main.lang:
ach, af, am, an, ar, as, ast, az, azz, be, bg, bn-BD, bn-IN, br, bs, ca, cak, crh, cs, cy, da, de, dsb, el, en-CA, en-GB, en-ZA, eo, es-AR, es-CL, es-ES, es-MX, et, eu, fa, ff, fi, fr, fy-NL, ga-IE, gd, gl, gn, gu-IN, he, hi-IN, hr, hsb, hto, hu, hy-AM, ia, id, is, it, ja, ka, kab, kk, km, kn, ko, lij, lo, lt, ltg, lv, mai, mk, ml, mr, ms, my, nb-NO, ne-NP, nl, nn-NO, nv, oc, or, pa-IN, pai, pbb, pl, pt-BR, pt-PT, qvi, rm, ro, ru, si, sk, sl, son, sq, sr, sv-SE, sw, ta, te, th, tl, tr, trs, uk, ur, uz, vi, wo, xh, zam, zh-CN, zh-TW, zu
```

Looking in the `www.mozilla.org` repo, I see no local changes in git. So I ran something, but not using the correct file it seems. 

Any ideas?

**Comment by flodolo** [comment]
>     2\. I had to manually move my fork of `www.mozilla.org` into parent directory which I called `mozilla-l10n`. I also had to rename the subfolder to `mozilla_org`.

This shouldn't be needed. Langchecker knows about the repository from Settings.php
See the last part here
https://github.com/mozilla-l10n/langchecker/blob/master/app/config/settings.inc.php.ini

You can override the default path, setting 

```PHP
$override_local = [
    'www.mozilla.org' => '/full/path/to/your/clone',
];
```

**Comment by alexgibson** [comment]
Ok, new commit added.

**Comment by flodolo** [comment]
Thanks, it looks good. I can take care of the cherry-pick to prod. In the future, we should just give you folks access to both repositories.

**Comment by flodolo** [comment]
Side note: don't force push, add commits on top. We squash when merging.

**Comment by alexgibson** [comment]
> I can take care of the cherry-pick to prod. In the future, we should just give you folks access to both repositories.

If we're to be responsible for this, I'd very much like to learn the full flow. Thanks @flodolo

**Comment by flodolo** [comment]
The problem is that we don't do pull requests and merges to production, and you need push permissions to cherry-pick and push. As said, we should just give you access once everything is clear.

**Comment by alexgibson** [comment]
> The problem is that we don't do pull requests and merges to production, and you need push permissions to cherry-pick and push. As said, we should just give you access once everything is clear.

Please let us know when this is set up, thanks.

**Comment by flodolo** [comment]
I've already done the cherry-pick, and created a team that has write access to both trunk and production repo, given I can trust you won't mess up with Git :)

**Comment by alexgibson** [comment]
Great, thanks @flodolo 👍

**Pull request merged**
