### PR TITLE
Download Firefox for other platforms

### PR DESCRIPTION
**Pull request by gaby2300**

### CODE REVIEW

**Comment by flodolo** [comment]
Any specific reason to not use Pontoon for mozilla.org translations?
https://pontoon.mozilla.org/es-AR/mozillaorg/

CC @deimidis 
The format is wrong, you added an extra line when you should have replaced the second, e.g.

WRONG
```
 ;Download Firefox for another platform
 Download Firefox for another platform
Descargá Firefox para otra plataforma
```

CORRECT
```
 ;Download Firefox for another platform
Descargá Firefox para otra plataforma
```

As it is, translations in this file will be unused and lost at the first update.

**Comment by gaby2300** [comment]
That was me, Gabriela. I'm very sorry Francesco! I tried to help but it
seems I made a mess. Should I change those strings to the correct way?

**Comment by gaby2300** [comment]
Will do Francesco, thanks! And again, very sorry for the mess in Github.

**Comment by flodolo** [comment]
Not a problem ;-)

**Pull request closed without merging**
